version: '3.4'

networks:
  besu-docker_besu-network:
    external: true

services:
  caliper:
    container_name: caliper
    image: hyperledger/caliper:0.5.1-unstable-20230521222045
    command: launch manager
    environment:
      - CALIPER_BIND_SUT=besu:latest
      - CALIPER_BENCHCONFIG=benchmarks/scenario/simple/config.yaml
      - CALIPER_NETWORKCONFIG=config-presc.json
    volumes:
      - .:/hyperledger/caliper/workspace
      - //var/run/docker.sock:/var/run/docker.sock
    networks:
      besu-docker_besu-network:
        ipv4_address: 172.16.239.6