version: '3.4'

networks:
  besu-docker_besu-network:
    external: true

services:
    caliper:
        container_name: caliper
        image: hyperledger/caliper:0.5.0
        command: launch manager
        environment:
          - CALIPER_BIND_SUT=besu:latest
          - CALIPER_BENCHCONFIG=benchmarks/scenario/simple/config.yaml
          - CALIPER_NETWORKCONFIG=config-presc.json
        volumes:
          - .:/hyperledger/caliper/workspace
        networks:
          besu-docker_besu-network:
            ipv4_address: 172.16.239.35