version: '3.4'

networks:
  besu-docker_besu-network:
    external: true

services:
  loadbalancer:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      besu-docker_besu-network:
        ipv4_address: 172.16.239.7
  caliper:
    container_name: caliper
    image: hyperledger/caliper:0.5.0
    command: launch manager
    environment:
      - CALIPER_BIND_SUT=besu:latest
      - CALIPER_BENCHCONFIG=benchmarks/scenario/simple/config.yaml
      - CALIPER_NETWORKCONFIG=config-presc.json
    volumes:
      - .:/hyperledger/caliper/workspace
      - //var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - loadbalancer
    networks:
      besu-docker_besu-network:
        ipv4_address: 172.16.239.6