version: "3.4"

networks:
  besu-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.239.0/24

services:
  node-1:
    container_name: node-1
    image: hyperledger/besu:23.4.4
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu --data-path=/opt/besu/data \
        --genesis-file=/opt/besu/genesis.json --rpc-http-enabled --rpc-http-port=8545 \
        --host-allowlist="*" --rpc-http-cors-origins="all" \
        --rpc-http-api=ADMIN, IBFT, QBFT, CLIQUE, ETH, NET, TXPOOL, WEB3 \
        --rpc-ws-enabled --rpc-ws-port=8546 --p2p-port=30303 --min-gas-price=0 \
        --miner-coinbase f17f52151EbEF6C7334FAD080c5704D77216b732;
    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - ./node-1/data:/opt/besu/data
    networks:
      besu-network:
        ipv4_address: 172.16.239.8
  node-2:
    container_name: node-2
    image: hyperledger/besu:23.4.4

    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 10;
        /opt/besu/bin/besu --data-path=/opt/besu/data \
         --genesis-file=/opt/besu/genesis.json \
         --config-file=/config/config.toml \
         --bootnodes=enode://3381dc91a1f9f7d7d7d193b2552534c3cb25d5334e20329cab64ddd571ef2dcb5b3f9215f5495fe843774dcd38d1587e34c82ebd24b8271a545d0e443aaa8f52@172.16.239.8:30303;

    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - ./node-2/data:/opt/besu/data
      - ./config.toml:/config/config.toml
    depends_on:
      - node-1
    networks:
      besu-network:
        ipv4_address: 172.16.239.9
  node-3:
    container_name: node-3
    image: hyperledger/besu:23.4.4

    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 10;
        /opt/besu/bin/besu --data-path=/opt/besu/data \
         --genesis-file=/opt/besu/genesis.json \
         --config-file=/config/config.toml \
         --bootnodes=enode://3381dc91a1f9f7d7d7d193b2552534c3cb25d5334e20329cab64ddd571ef2dcb5b3f9215f5495fe843774dcd38d1587e34c82ebd24b8271a545d0e443aaa8f52@172.16.239.8:30303;

    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - ./node-3/data:/opt/besu/data
      - ./config.toml:/config/config.toml
    depends_on:
      - node-1
    networks:
      besu-network:
        ipv4_address: 172.16.239.10
  node-4:
    container_name: node-4
    image: hyperledger/besu:23.4.4

    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 10;
        /opt/besu/bin/besu --data-path=/opt/besu/data \
         --genesis-file=/opt/besu/genesis.json \
         --config-file=/config/config.toml \
         --bootnodes=enode://3381dc91a1f9f7d7d7d193b2552534c3cb25d5334e20329cab64ddd571ef2dcb5b3f9215f5495fe843774dcd38d1587e34c82ebd24b8271a545d0e443aaa8f52@172.16.239.8:30303;

    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - ./node-4/data:/opt/besu/data
      - ./config.toml:/config/config.toml
    depends_on:
      - node-1
    networks:
      besu-network:
        ipv4_address: 172.16.239.11
  node-5:
    container_name: node-5
    image: hyperledger/besu:23.4.4

    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 10;
        /opt/besu/bin/besu --data-path=/opt/besu/data \
         --genesis-file=/opt/besu/genesis.json \
         --config-file=/config/config.toml \
         --bootnodes=enode://3381dc91a1f9f7d7d7d193b2552534c3cb25d5334e20329cab64ddd571ef2dcb5b3f9215f5495fe843774dcd38d1587e34c82ebd24b8271a545d0e443aaa8f52@172.16.239.8:30303;

    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - ./node-5/data:/opt/besu/data
      - ./config.toml:/config/config.toml
    depends_on:
      - node-1
    networks:
      besu-network:
        ipv4_address: 172.16.239.12
  node-6:
    container_name: node-6
    image: hyperledger/besu:23.4.4

    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 10;
        /opt/besu/bin/besu --data-path=/opt/besu/data \
         --genesis-file=/opt/besu/genesis.json \
         --config-file=/config/config.toml \
         --bootnodes=enode://3381dc91a1f9f7d7d7d193b2552534c3cb25d5334e20329cab64ddd571ef2dcb5b3f9215f5495fe843774dcd38d1587e34c82ebd24b8271a545d0e443aaa8f52@172.16.239.8:30303;

    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - ./node-6/data:/opt/besu/data
      - ./config.toml:/config/config.toml
    depends_on:
      - node-1
    networks:
      besu-network:
        ipv4_address: 172.16.239.13
