version: "3.4"

networks:
  besu-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.239.0/24

services:
  bootnode:
    container_name: bootnode
    image: hyperledger/besu:23.4.4
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu --data-path=/opt/besu/data \
        --genesis-file=/opt/besu/genesis.json --rpc-http-enabled --rpc-http-port=8545 \
        --host-allowlist="*" --rpc-http-cors-origins="all" \
        --rpc-http-api=ADMIN, IBFT, QBFT, CLIQUE, ETH, NET, TXPOOL, WEB3;
    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - ./node-1/data:/opt/besu/data
    networks:
      besu-network:
        ipv4_address: 172.16.239.30
  node-2:
    container_name: node-2
    image: hyperledger/besu:23.4.4

    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 10;
        /opt/besu/bin/besu --data-path=/opt/besu/data \
         --genesis-file=/opt/besu/genesis.json \
         --config-file=/config/config.toml \
         --bootnodes=enode://59ef8b79beebfeb8676e03b9893ab280ecdc900732b3fa4244aab5569c9278afbbf671963ca90ed18ed6571b3809432a0f1cb478c10b1bebc0bbad543fc7062c@172.16.239.30:30303 --p2p-port=30303;

    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - ./node-2/data:/opt/besu/data
      - ./log-config.xml:/config/log-config.xml
      - ./config.toml:/config/config.toml
    depends_on:
      - bootnode
    networks:
      besu-network:
        ipv4_address: 172.16.239.31
  node-3:
    container_name: node-3
    image: hyperledger/besu:23.4.4

    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 10;
        /opt/besu/bin/besu --data-path=/opt/besu/data \
         --genesis-file=/opt/besu/genesis.json \
         --config-file=/config/config.toml \
         --bootnodes=enode://59ef8b79beebfeb8676e03b9893ab280ecdc900732b3fa4244aab5569c9278afbbf671963ca90ed18ed6571b3809432a0f1cb478c10b1bebc0bbad543fc7062c@172.16.239.30:30303 --p2p-port=30303;

    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - ./node-3/data:/opt/besu/data
      - ./log-config.xml:/config/log-config.xml
      - ./config.toml:/config/config.toml
    depends_on:
      - bootnode
    networks:
      besu-network:
        ipv4_address: 172.16.239.32
  node-4:
    container_name: node-4
    image: hyperledger/besu:23.4.4

    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 10;
        /opt/besu/bin/besu --data-path=/opt/besu/data \
         --genesis-file=/opt/besu/genesis.json \
         --config-file=/config/config.toml \
         --bootnodes=enode://59ef8b79beebfeb8676e03b9893ab280ecdc900732b3fa4244aab5569c9278afbbf671963ca90ed18ed6571b3809432a0f1cb478c10b1bebc0bbad543fc7062c@172.16.239.30:30303 --p2p-port=30303;

    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - ./node-4/data:/opt/besu/data
      - ./log-config.xml:/config/log-config.xml
      - ./config.toml:/config/config.toml
    depends_on:
      - bootnode
    networks:
      besu-network:
        ipv4_address: 172.16.239.33
  node-5:
    container_name: node-5
    image: hyperledger/besu:23.4.4

    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 10;
        /opt/besu/bin/besu --data-path=/opt/besu/data \
         --genesis-file=/opt/besu/genesis.json \
         --config-file=/config/config.toml \
         --bootnodes=enode://59ef8b79beebfeb8676e03b9893ab280ecdc900732b3fa4244aab5569c9278afbbf671963ca90ed18ed6571b3809432a0f1cb478c10b1bebc0bbad543fc7062c@172.16.239.30:30303 --p2p-port=30303;

    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - ./node-5/data:/opt/besu/data
      - ./log-config.xml:/config/log-config.xml
      - ./config.toml:/config/config.toml
    depends_on:
      - bootnode
    networks:
      besu-network:
        ipv4_address: 172.16.239.34
  node-6:
    container_name: node-6
    image: hyperledger/besu:23.4.4

    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 10;
        /opt/besu/bin/besu --data-path=/opt/besu/data \
         --genesis-file=/opt/besu/genesis.json \
         --config-file=/config/config.toml \
         --bootnodes=enode://59ef8b79beebfeb8676e03b9893ab280ecdc900732b3fa4244aab5569c9278afbbf671963ca90ed18ed6571b3809432a0f1cb478c10b1bebc0bbad543fc7062c@172.16.239.30:30303 --p2p-port=30303;

    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - ./node-6/data:/opt/besu/data
      - ./log-config.xml:/config/log-config.xml
      - ./config.toml:/config/config.toml
    depends_on:
      - bootnode
    networks:
      besu-network:
        ipv4_address: 172.16.239.35
