version: '3.4'

networks:
  besu-docker_besu-network:
    external: true

services:
  loadbalancer:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      besu-docker_besu-network:
        ipv4_address: 172.16.239.7